{
 "title": "Vuls",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "severity",
    "label": "Severity",
    "query": {
     "query": "label_values(vulns{}, severity)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(servers{}, serverName)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Severities (Grouped by scores)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Severities",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (severity) (servers{serverName=~\"${server:pipe}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Severities (Grouped by servers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "$server",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "repeat": "server",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count({serverName=~\"${server:pipe}\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vulnerabilities per Server",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (serverName) (servers{serverName=~\"${server:pipe}\"})",
     "legendFormat": "{{serverName}}"
    },
    {
     "expr": "sum (servers{serverName=~\"${server:pipe}\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Servers overview",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (severity, serverName, hostname) (servers{serverName=~\"${server:pipe}\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Found CVEs by Severity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 7, "y": 28 },
   "targets": [
    {
     "expr": "sum by (severity) (servers{serverName=~\"${server:pipe}\"})",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Found CVEs Overview",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by (cveID, severity, fixState, packageName, summary) (vulns{severity!=\"\"})"
    }
   ]
  }
 ]
}